name: Build and Release ZIP

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version from tag
        id: version
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Create dist folder
        run: mkdir -p dist

      - name: Build plugin zip
        run: |
          zip -r "dist/wc-mobile-accordion-menu-${{ steps.version.outputs.tag }}.zip" wc-mobile-accordion-menu -x '*/.*'

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: WC Mobile Accordion Menu ${{ steps.version.outputs.tag }}
          draft: false
          prerelease: false
          files: |
            dist/wc-mobile-accordion-menu-${{ steps.version.outputs.tag }}.zip